export const envConstant = {
  nodeEnv: 'NODE_ENV',
  appBaseUrl: 'APP_BASE_URL',
  appPort: 'APP_PORT',
  mailboxPort: 'MAILBOX_PORT',
  telegramBotToken: 'TELEGRAM_BOT_TOKEN',
  telegramBotId: 'TELEGRAM_BOT_ID',
  mailboxHost: 'MAILBOX_HOST',
  mailbox: 'MAILBOX',
  emailPassword: 'EMAIL_PASSWORD',
  contactEmail: 'CONTACT_EMAIL',
  dbHost: 'DB_HOST',
  dbPort: 'DB_PORT',
  dbUser: 'DB_USER',
  dbPassword: 'DB_PASSWORD',
  dbName: 'DB_NAME',
};
