export const envConstant = {
  nodeEnv: 'NODE_ENV',
  appBaseUrl: 'APP_BASE_URL',
  appPort: 'APP_PORT',
  telegramBotToken: 'TELEGRAM_BOT_TOKEN',
  testTelegramBotToken: 'TEST_TELEGRAM_BOT_TOKEN',
  mailboxHost: 'MAILBOX_HOST',
  mailboxPort: 'MAILBOX_PORT',
  mailbox: 'MAILBOX',
  emailPassword: 'EMAIL_PASSWORD',
  contactEmail: 'CONTACT_EMAIL',
  dbHost: 'DB_HOST',
  testDbHost: 'TEST_DB_HOST',
  dbPort: 'DB_PORT',
  testDbPort: 'TEST_DB_PORT',
  dbUser: 'DB_USER',
  testDbUser: 'TEST_DB_USER',
  dbPassword: 'DB_PASSWORD',
  testDbPassword: 'TEST_DB_PASSWORD',
  dbName: 'DB_NAME',
  testDbName: 'TEST_DB_NAME',
};
